spring:
  config:
    activate:
      on-profile: secret

  datasource:
    username: root
    password: qwer1234!

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 22712048078-adg5cb526a0gmvntlji4htg95updcroq.apps.googleusercontent.com
            client_secret: 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
            scope: email, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

jwt:
  secret: 767963a3e68e579a9a6e1e5e1ccbf48cea6948c778d26c3b2bc58513115e66417418a854fe84116997400c510fad2ebae400e74171f977d732ba266a001dd388